xn.create("renren.renrenAPIConfig",[],function(){
	
	var CONFIG = {
			/*apiServerURL:"http://mc1.test.renren.com/mlogin/xn_api_test/api",*/
			refreshTokenURL:"http://mc1.test.renren.com/mlogin/xn_api_test/",
			apiServerURL:"http://mc2.test.renren.com/api",
			authorizeURL:"https://login.renren.com/mlogin/auth/auth",
			SCOPE_FIELD:{
		    	read_user_blog:"read_user_blog",
		    	read_user_checkin:"read_user_checkin",
		    	read_user_feed:"read_user_feed",
		    	read_user_guestbook:"read_user_guestbook",
		    	read_user_invitation:"read_user_invitation",
		    	read_user_like_history:"read_user_like_history",
		    	read_user_message:"read_user_message",
		    	read_user_notification:"read_user_notification"
		    },
		    FEED_TYPE:{
		    	SHARE_BLOG:102,
		    	SHARE_PHOTO:103,
		    	SHARE_ALBUM:104,
		    	SHARE_LINK:107,
		    	SHARE_VIDEO:110,
		    	HEAD_UPDATE:501,
		    	STATUS_UPDATE:502,
		    	BLOG_PUBLISH:601,
		    	PHOTO_PUBLISH_ONE:701,
		    	PHOTO_TAG_PUBLISH:702,
		    	PHOTO_PUBLISH_MORE:709,
		    	GIFT_GIVE:801,
		    	LBS_SIGNIN:1101,
		    	LBS_EVALUATION:1104,
		    	PAGE_JOIN:2002,
		    	SHARE_PAGE_BLOG:2003,
		    	SHARE_PAGE_PHOTO:2004,
		    	PAGE_SHARE_LINK:2005,
		    	PAGE_SHARE_VIDEO:2006,
		    	PAGE_STATUS_UPDATE:2008,
		    	SHARE_PAGE_ALBUM:2009,
		    	PAGE_BLOG_PUBLISH:2012,
		    	PAGE_PHOTO_PUBLISH:2013,
		    	PAGE_HEADPHOTO_UPDATE:2015,
		    	MINI_SITE_SHARE_BLOG:3801,
		    	MINI_SITE_SHARE_VIDEO:3802,
		    	MINI_SITE_SHARE_PHOTO:3803,
		    	MINI_SITE_SHARE_LINK:3804,
		    	EDM_TEXT:8001,
		    	EDM_PHOTO:8002,
		    	EDM_VIDEO:8003,
		    	EDM_FLASH:8004,
		    	CHEWEN_PUBLISH_PHOTO:8905,
		    	CHEWEN_PUBLISH_NEWS:8906
		    },
		    APIMap:{
		    	baseRequire:{
		    		sig:null,
		    		v:"1.0",
		    		access_token:null,
		    		format:"json"
		    	},
		    	feed:{
		    		publishFeed:{
		    			required:{
		    				title:{
		    					max_length:30
		    				},
		    				url:null,
		    				content:null
		    			},
		    			optional:{
		    				image_src:null,//新鲜事图片地址
		    				message:{
		    					max_length:200//用户输入的话，长度不能超过200字
		    				}
		    			}
		    		}
		    	},
		    	profile:{
		    		getInfo:{
		    			required:null,
		    			optional:{
		    				uid:null//指定用户的UID,没有指定取当前登录用户的
		    			}
		    		}
		    	}
		    }
			
	};
	
	return CONFIG;
	
});